---
- hosts: all
  sudo_user: isucon
  sudo: yes
  tasks:
    - command: git clone https://github.com/tagomoris/xbuild.git /home/isucon/.xbuild
      args:
        creates: /home/isucon/.xbuild/ruby-install

    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.1.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /home/isucon/env.sh gem install --no-rdoc --no-ri foreman
      args:
        creates: /home/isucon/.local/ruby/bin/foreman
    - command: /home/isucon/env.sh bundle install
      args:
        chdir: /home/isucon/webapp/ruby
