---
- hosts: imageservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.5.0 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
